### ISSUE TITLE
Procedures / Functions needed

### ISSUE THREAD

**Issue by Toan-Anh** [hkhoi/EVENet-Database#8]
The following functionalities are currently needed:
- Check if the password of a user is correct.
- Set an individual's/organizer's information (full name, birthday, ... / company name, slogan, ...) (Because a user only need an email to create an account first, information that are specific to an Individual/Organizer will be set later).
- Check if a User is created, but Individual / Organization information for that user is not fully set up.

**Comment by hkhoi** [comment]
@Toan-Anh : Users have to choose their type immediately at registration, so setIndividual is just for editing their information
bool auth(username, password)  -> hkhoi.sql
setIndividual(username, blah blah, blah blah...)
getIndividual(username)
